import fs from 'fs'

const { targetUrl, violations } = JSON.parse(fs.readFileSync('designguard-results.json'))
const screenshotName = targetUrl.includes('news.ycombinator.com') ? 'hackernews-screenshot.png' : targetUrl.includes('irs.gov') ? 'irs-screenshot.png' : 'designguard-screenshot.png'
const screenshotBase64 = fs.readFileSync(screenshotName).toString('base64')
const impactColor = { critical: '#ff4d4f', serious: '#ff9800', moderate: '#ffc107', minor: '#8bc34a' }

const rows = violations.map(v => `
  <div class="card">
    <div class="card-head">
      <span class="badge" style="background:${impactColor[v.impact] || '#999'}">${v.impact.toUpperCase()}</span>
      <span class="rule">${v.id}</span>
    </div>
    <p>${v.description}</p>
    <span class="count">${v.nodes.length} affected element${v.nodes.length > 1 ? 's' : ''}</span>
  </div>
`).join('\n')

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>DesignGuard Report</title>
<style>
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; background: #0d0d0f; color: #eee; margin: 0; padding: 40px; }
  .logo { display:flex; align-items:center; gap:12px; margin-bottom: 8px; }
  .logo-icon { width:40px; height:40px; border-radius:10px; background:linear-gradient(135deg,#6a5cff,#00d4ff); display:flex; align-items:center; justify-content:center; font-weight:bold; font-size:20px; }
  h1 { margin: 0; font-size: 28px; }
  .subtitle { color: #999; margin-bottom: 30px; }
  .target { color:#00d4ff; word-break: break-all; }
  .screenshot { max-width: 100%; border: 1px solid #333; border-radius: 10px; margin-bottom: 40px; }
  .summary { display:flex; gap:20px; margin-bottom: 30px; flex-wrap: wrap; }
  .stat { background:#1a1a1e; padding:16px 24px; border-radius:10px; }
  .stat .num { font-size:28px; font-weight:bold; }
  .stat .label { color:#999; font-size:13px; }
  .card { background:#1a1a1e; border-radius:10px; padding:18px 20px; margin-bottom:14px; border-left: 4px solid #444; }
  .card-head { display:flex; align-items:center; gap:10px; margin-bottom:8px; }
  .badge { font-size:11px; font-weight:bold; padding:3px 8px; border-radius:6px; color:#000; }
  .rule { font-family: monospace; color:#00d4ff; }
  .card p { margin: 6px 0; color:#ccc; }
  .count { font-size: 12px; color:#888; }
  footer { margin-top:40px; color:#555; font-size:12px; }
</style>
</head>
<body>
  <div class="logo">
    <div class="logo-icon">DG</div>
    <h1>DesignGuard</h1>
  </div>
  <div class="subtitle">Automated accessibility audit &middot; Target: <span class="target">${targetUrl}</span></div>

  <div class="summary">
    <div class="stat"><div class="num">${violations.length}</div><div class="label">Violations Found</div></div>
    <div class="stat"><div class="num">${violations.reduce((a, v) => a + v.nodes.length, 0)}</div><div class="label">Affected Elements</div></div>
    <div class="stat"><div class="num">WCAG 2.0 A/AA</div><div class="label">Standard Used</div></div>
  </div>

  <img class="screenshot" src="data:image/png;base64,${screenshotBase64}" alt="Screenshot of scanned page" />

  <h2>Violations</h2>
  ${rows || '<p style="color:#8bc34a">No violations found — great job!</p>'}

  <footer>Generated by DesignGuard &middot; automated WCAG 2.0 A/AA accessibility auditing</footer>
</body>
</html>`

fs.writeFileSync('designguard-report.html', html)
console.log('Report saved: designguard-report.html — run "open designguard-report.html" to view it.')